name: Notion Database Backup

on:
  schedule:
    - cron: '0 8 * * 1' # Runs at 8:00 UTC every Monday
  workflow_dispatch: # Allows manual runs

jobs:
  backup:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Notion SDK
        run: npm install @notionhq/client@2.2.14

      - name: Step 1: Fetch and Save Notion Data as JSON
        run: node fetch_json.js
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_TOOLS_DB_ID: ${{ secrets.NOTION_TOOLS_DB_ID }}
          NOTION_LITERATURE_DB_ID: ${{ secrets.NOTION_LITERATURE_DB_ID }}
          NOTION_TRAINING_DB_ID: ${{ secrets.NOTION_TRAINING_DB_ID }}
          NOTION_USE_CASES_DB_ID: ${{ secrets.NOTION_USE_CASES_DB_ID }}

      - name: Step 2: Convert JSON to CSV
        run: node convert_csv.js

      - name: Step 3: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Automated Notion backup (JSON + CSV) [$(date)]" || echo "No changes to commit"
          git push
